### PR TITLE
R&D fixed some internal API port issues (25052022)

### PR DESCRIPTION
**Pull request by beibeiJ**
R&D has found and fixed some internal API port issues

### CODE REVIEW

**Review by gtema — COMMENTED** [review]
ugh, damn. This one is again huge. Let's see how wizard stick deals with that

**Comment by beibeiJ** [comment]
> 

Yes. I saw 9 files have been changed. Our squad has not started the content review so we can only trust that R&D found the issues and fixed them.

**Comment by gtema** [comment]
yeah, but for 9 files "+1,296 −1,955" lines changed is real lot.

**Review by gtema — DISMISSED** [review]

**Comment by gtema** [comment]
hehe, here we see 9 files changed, in https://github.com/opentelekomcloud-docs/modelarts/pull/37 already 39 (mostly deletes)

**Comment by beibeiJ** [comment]
@gtema based on the review feedback on https://github.com/opentelekomcloud-docs/modelarts/pull/37, the vendor has returned with a new version of API documents. As suggested by @vladimirhasko , I have committed to the same pull request. To have the latest changes on https://github.com/opentelekomcloud-docs/modelarts/pull/37, what shall we do? Does someone need to post the new commits to reflect the changes?

**Review by gtema — APPROVED** [review]

**Comment by beibeiJ** [comment]
Created a new pull request on Gitea: https://gitea.eco.tsi-dev.otc-service.com/docs/doc-exports/pulls/26

**Pull request closed without merging**
